### ISSUE TITLE
Cannot find upper-cased file in linux

### ISSUE THREAD

**Issue by zaaack** [reasonml-community/bs-loader#19]
bsb will compile upper-cased file to lower case e.g. TodoApp.re => todoApp.js in linux, see: https://github.com/BuckleScript/bucklescript/issues/913

then webpack throw an error: cannot find src/todoApp in ....
![_ _20170812225455](https://user-images.githubusercontent.com/5233940/29241705-5536035c-7fb1-11e7-903d-73a6099bab30.png)

Is there a way to work around this?

**Comment by rrdelaney** [comment]
Thanks for reporting this!

There should be a pretty easy bug fix - just detect if the OS is Linux and always require a lowercased file name if it is. I can probably have this out today 😄

In the meantime, if you use lowercase file names does everything work?

**Comment by zaaack** [comment]
@rrdelaney Yes, lower case works fine!

**Comment by zaaack** [comment]
By the way, it's also a macos problem as the bucklescript issue says....

**Comment by rrdelaney** [comment]
Although it compiles different cases, I think MacOS isn't case-sensitive, so the require should still go through. That's been my experience with bs-loader so far.

**Comment by zaaack** [comment]
OK. I have a macOS machine but haven't try it  yet.

**Comment by rrdelaney** [comment]
@zaaack Can you try using the latest version, `1.5.9`?

**Comment by zaaack** [comment]
@rrdelaney Thanks for your quick fix! I'll try this later. But I'm not sure this can fix, because the problem is webpack cannot find "src/todoApp" in source folder, the require code emited by bucklescript is lower cased already, and doesn't have problem in lib folder it self.

**Comment by rrdelaney** [comment]
You're right! 🤦‍♂️ I solved the problem they _were_ having in the issue you linked - sorry for the misunderstanding!

**Comment by zaaack** [comment]
I have to admit I can be more clear before and sorry for that. Thanks for your time, again!

**Comment by rrdelaney** [comment]
I think this is going to be solved upstream when BuckleScript introduces [namespaces](https://github.com/BuckleScript/bucklescript/issues/1805). Do you think it would be ok to warn for now when we encounter an uppercased file on Linux?

**Comment by zaaack** [comment]
@rrdelaney Yeah, I think it's ok to warn for now.

**Comment by rrdelaney** [comment]
I think [`BuckleScript #1964`](https://github.com/BuckleScript/bucklescript/pull/1964) fixed this

@zaaack Can you check that? It should be released in BuckleScript v1.9.2

**Comment by zaaack** [comment]
@rrdelaney I tried bs-platform@v1.9.2, it fixed! 

But I got an error when `npm install bs-loader`, looks like package.json has some conflicts:
https://github.com/reasonml-community/bs-loader/blob/master/package.json#L1-L8

**Comment by rrdelaney** [comment]
Sorry about that 😅 should be all good in the latest version!
