### ISSUE TITLE
EOF errors

### ISSUE THREAD

**Issue by kennetpostigo** [reasonml-community/bs-loader#2]
Hey so I'm using `bs-loader` within a project called [qnd](https://github.com/kennetpostigo/qnd). I'm stress testing `qnd` right now on the kanban project found in the examples of the repo. If I feed qnd reason files for the entry file they are passed through `bs-loader` and then bucklescript will throw `END OF FILE` errors. If I instead feed `qnd` the bs output there are no errors. Any clue why this may be going on?

**Comment by rrdelaney** [comment]
Sorry I didn't see these issues! They got buried in my Github stream.

`END OF FILE` is a weird error to see. The only thing I can think off of the top of my head that would be different is `process.cwd()` - bs-loader uses this to find files.

Is there a difference in how qnd loads reason files vs. how `bsb` loads reason files?

**Comment by kennetpostigo** [comment]
@rrdelaney nope I set bs-loader up the same way you did in the readme. It's weird to see this and I just couldn't figure it out. Heres where the example for qnd lives: https://github.com/kennetpostigo/qnd/tree/master/example

if you want to see qnd setup of bs-loader its here https://github.com/kennetpostigo/qnd/blob/master/src/index.js#L59-L64

**Comment by rrdelaney** [comment]
Have you find out anything more?

**Comment by kennetpostigo** [comment]
No, I've tried to reproduce EOF errors on a dummy fibonacci program but couldn't. Thought the example project I linked above can be reproduced if you build it. I'll have some more time next week to debug more and try to reproduce on larger example projects.

**Comment by rrdelaney** [comment]
@kennetpostigo Is this still a problem for you?

**Comment by cxa** [comment]
I also encountered this error occasionally.

**Comment by rrdelaney** [comment]
@cxa Is there anyway to get it consistently?

**Comment by cxa** [comment]
I can reproduce it by cleaning project, build again, cancel it before build finished, and build again. But not every time, and my project is not a small one.

**Comment by rrdelaney** [comment]
Sounds weird, I'll see if I can get it to show up

**Comment by cxa** [comment]
I think it may related to the first build, the `bsb -make-world` run so many times on loading each `re|ml` file. If we can ensure `bsb -make-world` run only once for the each build that will be no problem.

**Comment by rrdelaney** [comment]
It's an optimization I'm already planning on 😄

**Comment by kennetpostigo** [comment]
I still see it occasionally, the app is pretty large too.

**Comment by rrdelaney** [comment]
@cxa I made the change to run `bsb -make-world` only once per compilation a few days ago, do you still see this problem?

**Comment by cxa** [comment]
@rrdelaney Used it whole day, not occurred such problem.

**Comment by rrdelaney** [comment]
Cool  - closing this out

**Comment by saschatimme** [comment]
This just happened for me in 3 tests runs twice (`bs-loader` used as a jest-transform) :(

**Comment by rrdelaney** [comment]
@saschatimme Does it also happen when using it with Webpack?

**Comment by rrdelaney** [comment]
Think this was related to a race condition that was recently fixed. Let me know if it happens again

**Comment by stfoo** [comment]
@rrdelaney, I have it a lot in my project while running dev-server. Every other build fails with:
```
Failed to compile.

./src/components/SomeComponent.re
    at Array.map (native)r: Fatal error: exception End_of_file
```

Not sure, but it could be related to upgrade of `bs-platform` to 3.0.0. 
Do you think it has something to do with bs-platform or is it some webpack issue?

**Comment by svoynow** [comment]
Just wanted to provide another data point that this is happening to me consistently on a fresh project using `bs-platform` 3.0.0

**Comment by rrdelaney** [comment]
@svoynow Can you try upgrading `bs-platform`? Also, what OS are you using?

**Comment by svoynow** [comment]
I misspoke above, I'm on the latest `bs-platform`, 3.1.5.
OS is Mac OS X 10.13.2

**Comment by tmattio** [comment]
Same issue here using `bs-platform` 3.1.4 and macOS 10.13.6.
