### ISSUE TITLE
jest doesn't work without testMatch config

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-loader#22]
Without a `testMatch` config in `package.json` bs-loader will pass along paths like `my-project/lib/js/lib/js/__tests__/foo_test.js` (note the duplicate `lib/js`), which obviously isn't going to be there. The correct path in this case should be `my-project/lib/js/__tests__/foo_test.js`

**Comment by rrdelaney** [comment]
Closing as a wontfix
