### ISSUE TITLE
Read bs-config instead of having webpack options

### ISSUE THREAD

**Issue by arnarthor** [reasonml-community/bs-loader#26]
By reading the bsconfig we could skip the options part of webpack.

The downside would be that bsconfig supports trailing commas and comments in JSON which we don't have access to AFAIK. 

I would really love this, since it could allow users to pick their style when using reason-scripts witouth ejecting it also prevents non reason-scripts users from making simple mistakes like, updating the options in webpack but not their bsconfig.

Do you have any thoughts on this @rrdelaney

**Comment by rrdelaney** [comment]
Sounds good 😄 I'm starting work on this now, just wrote a quick lib to read a `bsconfig.json` from a dir: https://github.com/rrdelaney/read-bsconfig

**Comment by arnarthor** [comment]
Awesome! Feel free to ping me if you want help with this, it should be pretty straight forward, but if you need extra time or eyes I'm available 👍

**Comment by rrdelaney** [comment]
This was fixed by #27
