### ISSUE TITLE
bs-loader doesn't work out-of-the-box with react bsb template

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-loader#32]
The react template that comes with bsb (`bsb -init <...> -theme react`) uses webpack1, which apparently isn't quite compatible with the recommended configuration for bs-loader. More specifically, the resolution algorithm seems to be different (it tries to resolve `foo.re.re` for some silly reason), and the loader might need to be configured differently as well. I didn't fool around with this too much before figuring I'd better look at what the example projects here are using (which is webpack3).

I think it might be a good idea to warn about webpack1 incompatibility, add a requirements section or some such thing, and perhaps we should also change the react template to avoid this confusion.

cc @chenglou

**Comment by chenglou** [comment]
Btw, @rrdelaney and I discussed about this, and we're thinking of dropping bs-loader as it is currently (or repurpose it) after the new bs comes out which allows you to compile to files with the suffix '.bs.js'. This plus in-source build means you can directly do `require('foo.bs')` without needing to instrument the require with a loader!

After that the only major convenience left from bs-loader would be that it auto-calls bsb inside the webpack pipeline, so that you don't have to maintain a second watcher, from bsb.

What do you think? Cc @bobzhang

**Comment by rrdelaney** [comment]
As @chenglou said, I think it’s a good idea to start moving away from a special loader to do all of this stuff, to much surface area for bugs. However a webpack plugin to set up a bsb runner sounds good to me 🙂

I’m working on moving the core bs-loader code to another package so we won’t be reimplementing as much moving to a plugin. You can see the progress on this is the “packages” directory. 

Back to the original issue though, I’ll update the README with a comparability warning.

**Comment by glennsl** [comment]
I thought bsb in the webpack pipeline was the primary purpose of bs-loader. I guess it has grown a bit in scope, but if I understand you correctly this will still be the primary purpose of the new "plugin" too? And if so, does a "plugin" mean something more tightly integrated that does not rely on this resolution mechanism? Or conversely, would it be so tightly integrated that it's even less compatible with webpack1?

**Comment by rrdelaney** [comment]
bs-loader is also for resolving the location of the generated file, as well as getting its contents. If bsb generates “foo.bs.js” and you “import ‘foo.bs’”, there’s no longer a need for custom resolution logic, only to run bsb in the background for convenience 🙂

I don’t know about webpack 1 compatibility  though, we should probably update the template anyway

**Comment by rrdelaney** [comment]
Closing as a wontfix. This is more on the bsb template's side
