### ISSUE TITLE
Workaround 'script' for WSL

### ISSUE THREAD

**Issue by superherointj** [reasonml-community/bs-loader#33]
'script' unix command is broken on WSL. And bs-loader uses it. This is what is breaking bs-loader on WSL. And all projects that uses bs-loader, including reason-scripts.

[Issue on BashOnWindows: script command fails, Function not implemented](https://github.com/Microsoft/BashOnWindows/issues/2053)

**Comment by superherointj** [comment]
https://github.com/Microsoft/BashOnWindows/issues/2053

**Comment by superherointj** [comment]
I've proposed this patch. If anyone care to test (on any environment). Have fun.
https://github.com/reasonml-community/bs-loader/pull/34/files

**Comment by rrdelaney** [comment]
reason-scripts should get patches without having to do anything 🙂

**Comment by rrdelaney** [comment]
Should be released now
