### ISSUE TITLE
"script" doesn't exist on some linuxes

### ISSUE THREAD

**Issue by jeffutter** [reasonml-community/bs-loader#35]
Alpine linux for example doesn't seem to come with the `script` command, nor is any kind of bsdutils package available. I use alpine in my build environment, I had the hardest time tracking down what

```
./src/index.re
/bin/sh: script: not found
```

meant. Anyhow, what benefit does that actually provide here? Would it be reasonable to disable it via ENV variable, or check if it is available in the PATH before trying to use it?

**Comment by rrdelaney** [comment]
Hi @jeffutter! Thanks for opening an issue 😄 we use “script” to capture highlighting of the BSB output. Without it most error messages from Super Errors wouldn’t be very usable. 

It looks like someone else had an issue using the “script” command in Alpine, the Github issue is here: https://github.com/gliderlabs/docker-alpine/issues/160. 

I recommend using BSB directly in your case. It seems like you have a fairly custom build environment, and it might be easier for you to take control of BuckleScript directly. I recommend using the newly released “.bs.js” insource compilation mode: https://github.com/BuckleScript/bucklescript/blob/master/Changes.md#1103. Let me know if you need help setting it up — you can message me on the Reason Discord server (discord.gg/reasonml) as @rrdelaney

**Comment by jeffutter** [comment]
@rrdelaney Ahh thank you for finding that. I ended up changing my build to use a Debian base and bs-loader works fine over there so I'm satisfied.

If more people run into this it might be useful to check that the "script" command exists and run without it including a clear warning "Your operating system doesn't have the 'script' command installed, bsb output will be missing colors until you install it" or something to that effect. It doesn't help that 'script' is really hard to search for (not your fault) :)

Anyway, thanks for the pointer. Hopefully, nobody else runs into this and if they do, hopefully, they can find this issue.
