### ISSUE TITLE
Hi any news on new release ?

### ISSUE THREAD

**Issue by OlegLustenko** [reasonml-community/bs-loader#37]
Hi, any news on shipping that feature?

https://github.com/reasonml-community/bs-loader/blob/9a946ab477e16e627b21a7c4fed2cead6e791bc7/packages/bs-loader/index.js#L32-L33

**Comment by rrdelaney** [comment]
Hi Oleg! You can try it out by installing `bs-loader@next` on npm. Let me know how it works out for you!

**Comment by OlegLustenko** [comment]
Hi, yes it helps!

**Comment by rrdelaney** [comment]
@oleglustenko have you had any problems with the beta? I’m thinking of promoting it to stable

**Comment by OlegLustenko** [comment]
@rrdelaney

I had issues with .merlin when i mixing ReasonML to existing JS app not sure if it relate to bs-loader. I going to check this in next few days

**Comment by OlegLustenko** [comment]
ok, it seems fine, my problem was related to https://github.com/reasonml-editor/vscode-reasonml/issues/76
